buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net/' }
        mavenCentral()
        maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:2.2-SNAPSHOT'
        classpath 'org.spongepowered:mixingradle:0.6-SNAPSHOT'
    }
}
apply plugin: 'net.minecraftforge.gradle.forge'
// Only edit below this line, the above code adds and enables the necessary things for Forge to be setup.
apply plugin: 'eclipse'
apply plugin: 'org.spongepowered.mixin'

version = '1.5.2'
group = 'ca.modmonster.minegit' // http://maven.apache.org/guides/mini/guide-naming-conventions.html
archivesBaseName = 'MineGIT'

sourceCompatibility = targetCompatibility = compileJava.sourceCompatibility = compileJava.targetCompatibility = '1.6'

minecraft {
    // The mappings can be changed at any time, and must be in the following format.
    // snapshot_YYYYMMDD   Snapshot are built nightly.
    // stable_#            Stables are built at the discretion of the MCP team.
    // Use non-default mappings at your own risk. they may not always work.
    // Simply re-run your setup task after changing the mappings to update your workspace.
    //mappings channel: 'snapshot', version: '20171003-1.12'
    mappings = "snapshot_20161220"
    version = "1.11.2-13.20.1.2588"
    runDir = "run"
}

repositories {
    mavenCentral()
    maven { url = 'https://repo.spongepowered.org/maven/' }
}

configurations {
    embed
    compile.extendsFrom(embed)
}

dependencies {
    // JGit
    embed "org.eclipse.jgit:org.eclipse.jgit:3.7.1.201504261725-r"

    // Apply Mixin AP (0.8.7 gives "unsupported class file major version 60")
    embed('org.spongepowered:mixin:0.8.3-SNAPSHOT') {
        exclude module: 'guava'
        exclude module: 'commons-io'
        exclude module: 'gson'
    }
}

processResources {
    inputs.property 'version', version

    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
        expand 'version': version
    }

    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}

sourceSets {
    main {
        refMap = "minegit.mixins.refmap.json"
    }
}

//mixin {
//    config "minegit.mixins.json"
//}

jar {
    from {
        configurations.embed.collect { it.isDirectory() ? it : zipTree(it) }
    } {
        exclude 'LICENSE.txt', 'META-INF/MANIFSET.MF', 'META-INF/maven/**', 'META-INF/*.RSA', 'META-INF/*.SF'
    }

    manifest.attributes(
            'ForceLoadAsMod': 'true',
            'FMLCorePluginContainsFMLMod': 'true',
            'TweakClass': 'org.spongepowered.asm.launch.MixinTweaker',
            'TweakOrder': '0'
    )
}

jar.finalizedBy('reobfJar')