# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

minecraft_version=b1.7.3
yarn_mappings=b1.7.3+build.8
loader_version=0.15.6-babric.2

# Mod Properties
mod_version=1.5.3
maven_group=ca.modmonster.minegit
archives_base_name=minegit